/**
 * Documentation content extracted from .docx files.
 * Each entry maps a slug to its HTML content.
 */

export interface DocArticle {
  slug: string;
  title: string;
  categoryIndex: number;
  html: string;
}

export const DOC_ARTICLES: DocArticle[] = [
  // ── 00 - Giới Thiệu ──
  {
    slug: "bat-dau-nhanh",
    title: "Bắt Đầu Nhanh",
    categoryIndex: 0,
    html: `<h1>Bắt Đầu Sử Dụng</h1><h2>Bước 1: Mở cửa sổ chat</h2><p>Người quản trị sẽ cung cấp cho bạn một trong các cách sau:</p><ul><li>Đường link trang web chat - mở bằng trình duyệt (Chrome, Firefox...)</li><li>Bot Telegram - tìm bot trong app Telegram và gửi tin nhắn</li><li>Bot Discord - vào server và chat trực tiếp</li></ul><h2>Bước 2: Gửi tin nhắn đầu tiên</h2><p>Cứ gõ bất kỳ gì bạn muốn. Ví dụ:</p><ul><li>"Xin chào" - OperisBot sẽ chào lại bạn</li><li>"Bạn là ai?" - OperisBot sẽ giới thiệu mình</li><li>"Giúp tôi tìm giá vàng hôm nay" - OperisBot sẽ tìm và trả lời</li></ul><h2>Bước 3: Thử các tính năng</h2><h3>Hỏi đáp</h3><ul><li>"GDP Việt Nam năm 2024 là bao nhiêu?"</li><li>"Giải thích Bitcoin đơn giản cho tôi"</li></ul><h3>Viết nội dung</h3><ul><li>"Viết cho tôi email xin nghỉ phép ngày mai"</li><li>"Viết caption Instagram cho ảnh du lịch Đà Lạt"</li></ul><h3>Tìm kiếm</h3><ul><li>"Tìm 5 nhà hàng ngon ở Quận 1"</li><li>"Tin tức công nghệ mới nhất hôm nay"</li></ul><h3>Nhắc nhở</h3><ul><li>"Nhắc tôi sau 30 phút uống nước"</li><li>"Mỗi sáng 8h gửi thời tiết cho tôi"</li></ul><h2>Mẹo sử dụng</h2><ul><li>Nói càng cụ thể càng tốt: 'Tìm giá iPhone 16 Pro Max trên Shopee' tốt hơn 'tìm điện thoại'</li><li>Có thể yêu cầu nhiều bước: 'Tìm 5 bài viết về AI, tóm tắt và lưu vào file'</li><li>Nếu kết quả chưa đúng ý, nói lại cụ thể hơn - OperisBot sẽ hiểu</li><li>OperisBot nhớ những gì bạn đã nói trong cuộc hội thoại - không cần nhắc lại</li></ul><h2>Câu hỏi thường gặp</h2><p><strong>H: Trợ lý có hiểu tiếng Việt không?</strong></p><p>Đ: Có! Hiểu và trả lời tiếng Việt hoàn toàn tự nhiên.</p><p><strong>H: Tôi có cần biết máy tính không?</strong></p><p>Đ: Chỉ cần biết gõ tin nhắn là đủ. Như nhắn tin Zalo/Messenger vậy.</p><p><strong>H: Dữ liệu của tôi có an toàn không?</strong></p><p>Đ: Có. Hệ thống chạy trên máy của bạn, dữ liệu không bị gửi đi đâu trừ khi bạn yêu cầu.</p><p><strong>H: Trợ lý có sai không?</strong></p><p>Đ: Có thể. Giống như hỏi một người, đôi khi câu trả lời chưa chính xác 100%. Nên kiểm tra lại thông tin quan trọng.</p>`,
  },
  {
    slug: "tong-quan-he-thong",
    title: "Tổng Quan Hệ Thống",
    categoryIndex: 0,
    html: `<h1>Giới Thiệu Hệ Thống OperisBot</h1><h2>Đây là gì?</h2><p>Đây là OperisBot - một trợ lý thông minh chạy trên máy tính của bạn. Bạn chỉ cần nhắn tin (chat) với nó, và nó sẽ giúp bạn làm nhiều việc khác nhau.</p><p>Hãy tưởng tượng bạn có OperisBot riêng của bạn, lúc nào cũng sẵn sàng, hiểu tiếng Việt, và có thể:</p><ul><li>Trả lời câu hỏi bất kỳ - giống như hỏi một người biết nhiều thứ</li><li>Tìm kiếm thông tin trên internet - tìm giá cả, tin tức, thời tiết...</li><li>Mở trang web và thao tác giúp bạn - click, gõ chữ, điền form, chụp ảnh màn hình</li><li>Tạo và chỉnh sửa file - tạo văn bản, bảng tính, báo cáo...</li><li>Nhắc nhở và làm việc tự động - hẹn giờ nhắc việc, kiểm tra định kỳ</li><li>Gửi tin nhắn qua Telegram, Discord... - thông báo khi có việc quan trọng</li></ul><h2>Tôi có cần biết lập trình không?</h2><p>KHÔNG. Bạn chỉ cần gõ tin nhắn bằng tiếng Việt bình thường, giống như đang nhắn tin với một người bạn. Ví dụ:</p><ul><li>"Hôm nay thời tiết thế nào?"</li><li>"Tìm giá iPhone 16 trên Shopee"</li><li>"Nhắc tôi lúc 3 giờ chiều họp"</li><li>"Tạo cho tôi một file báo cáo"</li></ul><h2>Nó chạy ở đâu?</h2><p>OperisBot chạy ngay trên máy tính của bạn (hoặc máy chủ của công ty). Dữ liệu của bạn KHÔNG bị gửi ra ngoài trừ khi bạn yêu cầu (ví dụ: tìm kiếm trên internet).</p><h2>Tôi giao tiếp với nó bằng cách nào?</h2><p>Bạn có thể chat với trợ lý qua:</p><ul><li>Trang web chat (webchat) - mở trình duyệt và gõ tin nhắn</li><li>Telegram - gửi tin nhắn qua app Telegram</li><li>Discord - chat trong server Discord</li><li>Hoặc các kênh khác tùy cấu hình</li></ul><p><em>Mọi thứ đều bằng tiếng Việt. Không cần học lệnh gì đặc biệt.</em></p>`,
  },

  // ── 01 - Khả Năng Cơ Bản ──
  {
    slug: "chat-va-hoi-dap",
    title: "Chat và Hỏi Đáp",
    categoryIndex: 1,
    html: `<h1>Hỏi Đáp và Viết Nội Dung</h1><h2>OperisBot có thể làm gì?</h2><p>Bạn có thể hỏi bất kỳ câu hỏi nào, nhờ viết bài, dịch ngôn ngữ, tính toán... Giống như có một người thông minh lúc nào cũng sẵn sàng giúp.</p><h2>Hỏi đáp kiến thức</h2><p>Hỏi bất kỳ điều gì bạn thắc mắc:</p><ul><li>"Tại sao trời mưa?" - giải thích hiện tượng tự nhiên</li><li>"Luật giao thông mới 2024 có gì thay đổi?" - cập nhật thông tin</li><li>"So sánh iPhone và Samsung cái nào tốt hơn?" - phân tích ưu nhược điểm</li><li>"Công thức tính lãi suất ngân hàng?" - hỗ trợ tính toán</li></ul><h2>Nhờ viết nội dung</h2><p>OperisBot viết giúp bạn nhiều loại văn bản:</p><ul><li>"Viết email xin nghỉ phép ngày mai" - email chuyên nghiệp</li><li>"Viết bài giới thiệu sản phẩm 200 từ" - bài viết marketing</li><li>"Viết thư cảm ơn khách hàng" - thư trang trọng, lịch sự</li><li>"Viết caption Instagram cho ảnh cafe" - nội dung mạng xã hội</li><li>"Viết mẫu hợp đồng thuê nhà" - văn bản pháp lý cơ bản</li></ul><h2>Dịch ngôn ngữ</h2><ul><li>"Dịch đoạn này sang tiếng Anh: ..." - dịch bất kỳ ngôn ngữ nào</li><li>"Email này nói gì? [dán email tiếng Anh]" - đọc và dịch giúp bạn</li></ul><h2>Tóm tắt và phân tích</h2><ul><li>"Tóm tắt bài viết này trong 3 dòng"</li><li>"So sánh phương án A và B, cái nào tốt hơn?"</li><li>"Phân tích ưu nhược điểm của việc mở quán cafe"</li></ul><h2>Tính toán</h2><ul><li>"Tính lãi suất vay 500 triệu trong 10 năm, lãi 8%/năm"</li><li>"100 USD bằng bao nhiêu VNĐ?"</li><li>"Tính chi phí xây nhà 100m2"</li></ul><h2>Lưu ý</h2><ul><li>OperisBot nhớ nội dung cuộc hội thoại - bạn có thể hỏi tiếp mà không cần nhắc lại</li><li>Thông tin về giá cả, thời tiết... cần dùng tính năng Tìm Kiếm Web (xem phần sau)</li><li>Đôi khi OperisBot có thể sai - nên kiểm tra lại thông tin quan trọng</li></ul>`,
  },
  {
    slug: "kiem-tra-may-tinh",
    title: "Kiểm Tra Máy Tính",
    categoryIndex: 1,
    html: `<h1>Kiểm Tra và Quản Lý Máy Tính</h1><h2>OperisBot có thể làm gì với máy tính?</h2><p>OperisBot có thể kiểm tra tình trạng máy tính, dọn dẹp file, nén file... Giống như có một kỹ thuật viên luôn sẵn sàng.</p><h2>Kiểm tra máy tính</h2><ul><li>"Ổ đĩa còn bao nhiêu dung lượng?" - xem ổ cứng đầy chưa</li><li>"Máy đang chạy nặng không?" - kiểm tra RAM, CPU</li><li>"Có chương trình nào đang chiếm CPU cao không?" - tìm ứng dụng nặng</li></ul><h2>Dọn dẹp và sắp xếp</h2><ul><li>"Liệt kê file trong thư mục Downloads" - xem có file gì</li><li>"Tìm file nào lớn hơn 1GB" - tìm file chiếm nhiều dung lượng</li><li>"Nén thư mục tài-liệu thành file zip" - nén file để gửi</li></ul><h2>Những việc OperisBot tự làm được</h2><p>Khi bạn yêu cầu, OperisBot sẽ tự chạy các lệnh trên máy tính. Bạn không cần biết lệnh gì - chỉ cần mô tả việc cần làm.</p><p>Ví dụ: Bạn nói 'Kiểm tra dung lượng ổ đĩa' - OperisBot sẽ tự biết cách kiểm tra và trả lời kết quả cho bạn.</p><h2>An toàn</h2><ul><li>Các việc đọc/kiểm tra (xem dung lượng, liệt kê file) là hoàn toàn an toàn</li><li>Trước khi làm việc nguy hiểm (xóa file, thay đổi hệ thống), OperisBot sẽ hỏi bạn trước</li><li>Nếu không chắc, hãy hỏi OperisBot 'Việc này có an toàn không?' trước khi đồng ý</li></ul>`,
  },
  {
    slug: "quan-ly-file",
    title: "Quản Lý File",
    categoryIndex: 1,
    html: `<h1>Tạo và Quản Lý File</h1><h2>OperisBot có thể làm gì với file?</h2><p>OperisBot có thể tạo file mới, đọc file có sẵn, chỉnh sửa nội dung, và xóa file trên máy tính của bạn. Giống như bạn nhờ OperisBot làm giúp việc soạn thảo.</p><h2>Tạo file mới</h2><p>Chỉ cần nói bạn muốn tạo gì:</p><ul><li>"Tạo file ghi chú với nội dung: Việc cần làm hôm nay" - tạo file văn bản</li><li>"Tạo file Word báo cáo trên Desktop" - tạo file Word</li><li>"Tạo danh sách khách hàng dạng Excel" - tạo file dữ liệu</li></ul><h2>Đọc file</h2><ul><li>"Đọc file báo-cáo.txt cho tôi"</li><li>"File này nói gì?" (kèm đường dẫn file)</li><li>"Mở file trên Desktop và đọc nội dung"</li></ul><h2>Sửa file</h2><ul><li>"Thêm dòng 'Họp 3h' vào file ghi-chú.txt"</li><li>"Đổi tên trong file từ 'Nguyễn Văn A' thành 'Nguyễn Văn B'"</li></ul><h2>Xóa file</h2><ul><li>"Xóa file tạm trên Desktop"</li></ul><p>OperisBot sẽ hỏi xác nhận trước khi xóa để tránh mất dữ liệu.</p><h2>File được lưu ở đâu?</h2><ul><li>Mặc định: trong thư mục làm việc của trợ lý</li><li>Bạn có thể chỉ định: 'Lưu trên Desktop', 'Lưu vào Documents'</li><li>OperisBot có thể làm việc với file ở bất kỳ đâu trên máy</li></ul><h2>Câu hỏi thường gặp</h2><p><strong>H: Có thể tạo file Word không?</strong></p><p>Đ: Có! OperisBot tạo được file Word (.docx) với định dạng đầy đủ.</p><p><strong>H: Có thể đọc file Excel không?</strong></p><p>Đ: Có! Đọc và xử lý dữ liệu trong file Excel.</p><p><strong>H: Có thể tạo file PDF không?</strong></p><p>Đ: Có thể tạo PDF từ trang web hoặc từ nội dung bạn yêu cầu.</p>`,
  },
  {
    slug: "tim-kiem-web",
    title: "Tìm Kiếm Web",
    categoryIndex: 1,
    html: `<h1>Tìm Kiếm Thông Tin Trên Internet</h1><h2>OperisBot có thể làm gì?</h2><p>OperisBot có thể tìm kiếm thông tin trên internet và đọc nội dung trang web giúp bạn. Giống như bạn nhờ ai đó lên Google tìm hộ.</p><h2>Tìm kiếm thông tin</h2><p>Hỏi bất kỳ gì bạn muốn biết:</p><ul><li>"Giá vàng hôm nay bao nhiêu?"</li><li>"Thời tiết TP.HCM ngày mai thế nào?"</li><li>"Tìm 5 nhà hàng ngon ở Đà Nẵng"</li><li>"Tin tức công nghệ mới nhất"</li><li>"So sánh giá iPhone 16 ở các cửa hàng"</li></ul><h2>Đọc nội dung trang web</h2><p>Nếu bạn có link bài viết, OperisBot đọc và tóm tắt giúp:</p><ul><li>"Đọc bài viết này cho tôi: https://..." - đọc và trình bày nội dung</li><li>"Tóm tắt trang web này" - rút gọn nội dung chính</li></ul><h2>Kết hợp: Tìm + Đọc + Tóm tắt</h2><p>Bạn có thể yêu cầu nhiều bước cùng lúc:</p><ul><li>"Tìm 5 bài viết về xu hướng AI 2025, đọc và tóm tắt cho tôi"</li><li>"Tìm giá vàng từ 3 nguồn khác nhau và so sánh"</li></ul><h2>Khi nào cần dùng tính năng này?</h2><ul><li>Khi bạn cần thông tin mới nhất (giá cả, tin tức, thời tiết...)</li><li>Khi bạn muốn đọc bài viết nhưng không có thời gian</li><li>Khi bạn muốn so sánh thông tin từ nhiều nguồn</li></ul><h2>Giới hạn</h2><ul><li>Một số trang web cần đăng nhập sẽ không đọc được bằng cách này</li><li>Một số trang web phức tạp cần dùng tính năng Điều Khiển Trình Duyệt (xem phần 02)</li></ul><p>Nếu OperisBot không đọc được trang web, bạn có thể yêu cầu nó 'Mở trình duyệt và đọc trang này' - sẽ dùng tính năng mạnh hơn.</p>`,
  },

  // ── 02 - Trình Duyệt Web ──
  {
    slug: "tong-quan-trinh-duyet",
    title: "Tổng Quan Trình Duyệt",
    categoryIndex: 2,
    html: `<h1>OperisBot Có Thể Điều Khiển Trình Duyệt Web</h1><h2>Điều này có nghĩa là gì?</h2><p>OperisBot có thể mở trình duyệt (Chrome), vào trang web, và làm mọi thứ giống như bạn đang tự làm: click chuột, gõ chữ, điền form, chụp ảnh màn hình...</p><p>Hãy tưởng tượng bạn ngồi bên cạnh một người và chỉ dẫn: 'Mở trang này, click vào nút kia, gõ cái này...' - trợ lý làm đúng như vậy.</p><h2>OperisBot có thể làm gì trên trình duyệt?</h2><ul><li>Mở bất kỳ trang web nào</li><li>Đọc nội dung trang web (kể cả trang phức tạp)</li><li>Click vào nút, link, menu</li><li>Gõ chữ vào ô tìm kiếm, form đăng ký</li><li>Điền form tự động (tên, email, số điện thoại...)</li><li>Chụp ảnh màn hình trang web</li><li>Tải file từ trang web</li><li>Cuộn trang, chuyển tab</li></ul><h2>3 cấp độ tương tác với internet</h2><h3>Cấp 1: Tìm kiếm nhanh (nhẹ nhất)</h3><p>Dùng khi: Bạn chỉ cần biết thông tin nhanh</p><ul><li>Ví dụ: "Giá vàng hôm nay?" - OperisBot tìm và trả lời ngay</li></ul><h3>Cấp 2: Đọc trang web</h3><p>Dùng khi: Bạn có link và muốn đọc nội dung</p><ul><li>Ví dụ: "Đọc bài viết này: https://..." - OperisBot đọc và tóm tắt</li></ul><h3>Cấp 3: Điều khiển trình duyệt (mạnh nhất)</h3><p>Dùng khi: Bạn cần tương tác với trang web (click, gõ, điền form)</p><ul><li>Ví dụ: "Mở Shopee, tìm iPhone 16, đọc giá" - trợ lý làm từng bước</li></ul><h2>2 chế độ hoạt động</h2><h3>Chế độ 1: Trình duyệt riêng</h3><p>OperisBot mở một cửa sổ trình duyệt riêng, KHÔNG ảnh hưởng đến trình duyệt cá nhân của bạn.</p><ul><li>Phù hợp cho: tự động lấy dữ liệu, kiểm tra website, chụp ảnh</li></ul><h3>Chế độ 2: Điều khiển Chrome của bạn (cần cài thêm Extension)</h3><p>Trợ lý điều khiển trực tiếp tab Chrome bạn đang mở. Giúp tương tác với trang đã đăng nhập sẵn.</p><ul><li>Phù hợp cho: đọc dữ liệu từ trang đã login (email, dashboard...)</li><li>Cần cài Chrome Extension (xem hướng dẫn riêng)</li></ul>`,
  },
  {
    slug: "chrome-extension",
    title: "Chrome Extension",
    categoryIndex: 2,
    html: `<h1>Điều Khiển Tab Chrome Của Bạn</h1><h2>Đây là gì?</h2><p>Bình thường, OperisBot mở trình duyệt riêng để làm việc. Nhưng đôi khi bạn muốn OperisBot tương tác với trang web mà bạn ĐÃ ĐĂNG NHẬP sẵn (ví dụ: email, Facebook, dashboard công ty...).</p><p>Tính năng này cho phép OperisBot điều khiển TRỰC TIẾP tab Chrome bạn đang mở.</p><h2>Khi nào cần dùng?</h2><ul><li>Bạn muốn OperisBot đọc email Gmail mà bạn đã đăng nhập</li><li>Bạn muốn OperisBot lấy số liệu từ dashboard công ty</li><li>Bạn muốn OperisBot tương tác với trang cần đăng nhập</li></ul><h2>Cách cài đặt (nhờ người quản trị hỗ trợ)</h2><h3>Bước 1:</h3><p>Người quản trị cài extension vào Chrome cho bạn</p><h3>Bước 2:</h3><p>Bạn sẽ thấy biểu tượng OperisBot trên thanh công cụ Chrome (góc phải trên)</p><h2>Cách sử dụng</h2><h3>BẬT: Cho phép OperisBot điều khiển tab</h3><ul><li>Mở tab bạn muốn OperisBot điều khiển</li><li>Click biểu tượng OperisBot trên thanh công cụ</li><li>Thấy chữ 'ON' = OperisBot có thể điều khiển tab này</li></ul><h3>TẮT: Ngắt kết nối</h3><ul><li>Click lại biểu tượng OperisBot</li><li>Chữ 'ON' mất = trợ lý không thể điều khiển nữa</li></ul><h2>Ý nghĩa các trạng thái</h2><ul><li>ON - Đã kết nối, OperisBot đang điều khiển tab</li><li>... - Đang kết nối, đợi một chút</li><li>! - Lỗi kết nối, kiểm tra hệ thống có đang chạy không</li></ul><h2>LƯU Ý BẢO MẬT QUAN TRỌNG</h2><p>Khi bật tính năng này, OperisBot có thể ĐỌC MỌI NỘI DUNG trên tab đó. Vì vậy:</p><ul><li>CHỈ bật cho tab bạn MUỐN OperisBot điều khiển</li><li>KHÔNG bật cho tab ngân hàng, tài khoản nhạy cảm trừ khi thật cần</li><li>Khi xong việc, NHỚ TẮT (click lại biểu tượng)</li><li>Nếu không chắc, hỏi người quản trị trước</li></ul>`,
  },
  {
    slug: "dieu-khien-trinh-duyet",
    title: "Điều Khiển Trình Duyệt",
    categoryIndex: 2,
    html: `<h1>Các Thao Tác Trên Trình Duyệt</h1><h2>Mở trang web</h2><p>Bạn chỉ cần nói:</p><ul><li>"Mở trang google.com"</li><li>"Mở Shopee"</li><li>"Mở trang facebook.com trong tab mới"</li></ul><h2>Chụp ảnh màn hình</h2><p>OperisBot chụp lại hình ảnh trang web đang hiển thị:</p><ul><li>"Chụp ảnh trang web này" - chụp phần đang thấy</li><li>"Chụp toàn bộ trang" - chụp cả phần phải cuộn xuống</li></ul><h2>Đọc nội dung trang</h2><ul><li>"Đọc nội dung trang này" - OperisBot đọc và trình bày lại</li><li>"Trang này có những gì?" - liệt kê các phần chính</li><li>"Có nút nào trên trang này?" - liệt kê các nút có thể click</li></ul><h2>Click vào nút hoặc link</h2><ul><li>"Click vào nút Đăng Nhập"</li><li>"Click vào link Xem Thêm"</li><li>"Click vào nút Mua Ngay"</li></ul><h2>Gõ chữ</h2><ul><li>"Gõ 'iPhone 16' vào ô tìm kiếm"</li><li>"Gõ email của tôi vào ô Email"</li><li>"Gõ xong rồi nhấn Enter"</li></ul><h2>Điền form tự động</h2><p>OperisBot có thể điền nhiều ô cùng lúc:</p><ul><li>"Điền form: Tên = Nguyễn Văn A, Email = abc@gmail.com, SĐT = 0901234567"</li><li>"Điền form đăng ký với thông tin của tôi"</li></ul><h2>Chọn trong danh sách (dropdown)</h2><ul><li>"Chọn 'Hà Nội' trong mục Thành Phố"</li><li>"Chọn 'Nam' trong mục Giới Tính"</li></ul><h2>Tải file và lưu PDF</h2><ul><li>"Tải file báo cáo trên trang này"</li><li>"Lưu trang này thành file PDF"</li></ul><h2>Xem trang trên điện thoại (giả lập)</h2><ul><li>"Xem trang này trên iPhone" - giả lập màn hình điện thoại</li><li>"Bật dark mode" - chuyển giao diện tối</li></ul><h2>Lưu ý quan trọng</h2><ul><li>Đôi khi OperisBot cần 1-2 giây để đọc trang trước khi thao tác</li><li>Một số trang có bảo vệ chống bot (captcha) có thể chặn trợ lý</li><li>Nếu thao tác lỗi, OperisBot sẽ thử lại hoặc báo cho bạn</li><li>Bạn có thể yêu cầu 'Chụp ảnh màn hình' bất kỳ lúc nào để xem OperisBot đang làm gì</li></ul>`,
  },
  {
    slug: "vi-du-trinh-duyet",
    title: "Ví Dụ Thực Tế",
    categoryIndex: 2,
    html: `<h1>Ví Dụ Thực Tế: Làm Gì Với Trình Duyệt?</h1><h2>Ví dụ 1: Kiểm tra giá sản phẩm</h2><h3>Bạn muốn:</h3><p>Biết giá iPhone 16 trên Shopee hiện tại</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mở Shopee, tìm iPhone 16 Pro Max, cho tôi biết giá 3 kết quả đầu tiên"</li></ul><h3>OperisBot sẽ:</h3><ul><li>Tự mở Shopee > gõ tìm kiếm > đọc giá > trả lời bạn</li></ul><h2>Ví dụ 2: Đọc tin tức mới</h2><h3>Bạn muốn:</h3><p>Biết tin tức nổi bật hôm nay mà không cần lướt nhiều trang</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mở VnExpress và Tuổi Trẻ, đọc 5 tin mới nhất mỗi trang, tóm tắt cho tôi"</li></ul><h3>OperisBot sẽ:</h3><ul><li>Mở từng trang > đọc tiêu đề và nội dung > tóm tắt thành 1 bản tin ngắn</li></ul><h2>Ví dụ 3: Điền form trực tuyến</h2><h3>Bạn muốn:</h3><p>Điền form đăng ký/khảo sát online</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mở form tại https://... và điền: Tên = Nguyễn Văn A, Email = a@gmail.com"</li></ul><h3>OperisBot sẽ:</h3><ul><li>Mở form > điền từng ô > gửi form</li></ul><h2>Ví dụ 4: Kiểm tra trang web của bạn</h2><h3>Bạn muốn:</h3><p>Biết trang web của công ty có hoạt động bình thường không</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mở trang https://mysite.com, chụp ảnh, và kiểm tra có lỗi gì không"</li></ul><h3>OperisBot sẽ:</h3><ul><li>Mở trang > chụp ảnh > kiểm tra lỗi > báo cáo kết quả</li></ul><h2>Ví dụ 5: Lấy dữ liệu từ trang đã đăng nhập</h2><h3>Bạn muốn:</h3><p>Lấy số liệu từ Google Analytics hoặc dashboard công ty</p><h3>Cách làm:</h3><ul><li>Bước 1: Mở Chrome, đăng nhập vào dashboard</li><li>Bước 2: Click biểu tượng Extension > ON</li><li>Bước 3: Nói với trợ lý: "Đọc số liệu trên trang này"</li><li>OperisBot sẽ đọc và tổng hợp dữ liệu cho bạn</li></ul>`,
  },

  // ── 03 - Tự Động Hóa ──
  {
    slug: "hen-gio-va-nhac-nho",
    title: "Hẹn Giờ và Nhắc Nhở",
    categoryIndex: 3,
    html: `<h1>Hẹn Giờ và Nhắc Nhở</h1><h2>OperisBot có thể làm gì?</h2><p>OperisBot có thể hẹn giờ nhắc nhở bạn, hoặc tự động làm việc gì đó vào thời gian bạn chỉ định. Giống như đặt báo thức thông minh - nhưng làm được nhiều hơn báo thức.</p><h2>Nhắc nhở 1 lần</h2><ul><li>"Nhắc tôi sau 30 phút uống nước"</li><li>"Nhắc tôi lúc 3 giờ chiều họp online"</li><li>"Nhắc tôi ngày mai 9h gửi báo cáo"</li><li>"Nhắc tôi thứ 6 nộp hồ sơ"</li></ul><h2>Nhắc nhở lặp lại</h2><ul><li>"Mỗi sáng 8h gửi thời tiết cho tôi"</li><li>"Mỗi 30 phút nhắc tôi nghỉ mắt"</li><li>"Mỗi thứ 2 lúc 9h nhắc tôi gửi report"</li><li>"Mỗi tối 10h tổng hợp tin tức"</li></ul><h2>Làm việc tự động theo lịch</h2><p>Không chỉ nhắc nhở, trợ lý còn có thể TỰ LÀM việc:</p><ul><li>"Mỗi sáng 7h tìm thời tiết TP.HCM và gửi cho tôi" - tự tìm và gửi</li><li>"Mỗi 10 phút kiểm tra trang web của tôi còn sống không" - tự kiểm tra và báo lỗi</li><li>"Mỗi tối 8h tìm tin tức công nghệ và tóm tắt" - tự tìm, đọc, tóm tắt</li></ul><h2>Quản lý nhắc nhở</h2><ul><li>"Liệt kê các nhắc nhở đang có" - xem danh sách</li><li>"Xóa nhắc nhở uống nước" - xóa nhắc nhở cũ</li><li>"Tạm dừng nhắc nhở kiểm tra web" - dừng tạm thời</li></ul><h2>Lưu ý</h2><ul><li>Nhắc nhở gửi qua kênh chat bạn đang dùng (webchat, Telegram, Discord)</li><li>Máy tính cần bật và hệ thống đang chạy để nhắc nhở hoạt động</li><li>Nhắc nhở 1 lần sẽ tự xóa sau khi chạy</li></ul>`,
  },
  {
    slug: "kiem-tra-dinh-ky",
    title: "Kiểm Tra Định Kỳ",
    categoryIndex: 3,
    html: `<h1>Tự Động Kiểm Tra Định Kỳ</h1><h2>Đây là gì?</h2><p>OperisBot có thể tự động 'thức dậy' mỗi 30 phút để kiểm tra xem có gì cần chú ý không. Nếu có - nó sẽ báo bạn. Nếu không có gì - nó im lặng, không làm phiền.</p><p>Giống như có một nhân viên tự giác, tự kiểm tra mọi thứ mà không cần ai nhắc.</p><h2>OperisBot có thể tự kiểm tra</h2><ul><li>Email mới quan trọng</li><li>Lịch họp sắp tới</li><li>Thời tiết nếu bạn sắp ra ngoài</li><li>Máy tính có vấn đề gì không (ổ cứng đầy, RAM cao)</li><li>Trang web của bạn còn hoạt động không</li></ul><h2>Cách thiết lập</h2><p>Bạn chỉ cần yêu cầu:</p><ul><li>"Mỗi 30 phút kiểm tra email và báo nếu có email quan trọng"</li><li>"Kiểm tra lịch và nhắc tôi 1 tiếng trước khi họp"</li><li>"Mỗi tiếng kiểm tra trang web của tôi"</li></ul><h2>Đặc điểm</h2><ul><li>Hoạt động ngầm - không làm phiền nếu không có gì</li><li>Chỉ gửi tin nhắn khi có việc cần chú ý</li><li>Ban đêm (23h-8h) OperisBot tự im trừ việc khẩn</li><li>Có thể gộp nhiều việc kiểm tra cùng lúc</li></ul><h2>Khác gì với Nhắc Nhở?</h2><p><strong>Nhắc nhở:</strong> 1 việc cụ thể, đúng giờ (VD: 3h chiều họp)</p><p><strong>Kiểm tra định kỳ:</strong> nhiều việc gộp lại, thời gian linh hoạt (~30 phút)</p>`,
  },
  {
    slug: "lam-viec-lon-o-nen",
    title: "Làm Việc Lớn Ở Nền",
    categoryIndex: 3,
    html: `<h1>Nhờ OperisBot Làm Việc Lớn Ở Nền</h1><h2>Đây là gì?</h2><p>Đôi khi bạn yêu cầu OperisBot làm việc phức tạp, mất nhiều thời gian (ví dụ: nghiên cứu 1 chủ đề, phân tích 50 trang web...). Thay vì bạn phải ngồi đợi, OperisBot sẽ:</p><ul><li>Tạo một 'OperisBot phụ' làm việc đó ở nền</li><li>Bạn vẫn tiếp tục chat bình thường</li><li>Khi xong, kết quả gửi về cho bạn</li></ul><h2>Khi nào nên dùng?</h2><ul><li>Công việc mất nhiều thời gian (5-30 phút)</li><li>Bạn muốn tiếp tục chat trong khi chờ kết quả</li><li>Công việc phức tạp cần tìm kiếm và phân tích nhiều nguồn</li></ul><h2>Ví dụ</h2><h3>Nghiên cứu chủ đề</h3><ul><li>"Nghiên cứu về xu hướng AI 2025 và gửi báo cáo cho tôi"</li></ul><p>OperisBot phụ sẽ: tìm 10+ bài viết > đọc > phân tích > tổng hợp báo cáo > gửi về cho bạn</p><h3>So sánh giá nhiều nguồn</h3><ul><li>"Tìm giá laptop dưới 20 triệu từ 5 trang web và so sánh"</li></ul><p>OperisBot phụ sẽ: mở từng trang > đọc giá > lập bảng so sánh > gửi kết quả</p><h3>Phân tích đối thủ</h3><ul><li>"Xem 10 trang web đối thủ và báo cáo họ làm gì mới"</li></ul><h2>Cách hoạt động</h2><ul><li>Bạn yêu cầu > Trợ lý chính tạo OperisBot phụ</li><li>OperisBot phụ chạy ngầm, bạn chat tiếp bình thường</li><li>Khi xong > Kết quả hiện lên trong cuộc chat của bạn</li></ul><h2>Lưu ý</h2><ul><li>Bạn có thể hỏi 'OperisBot phụ làm xong chưa?' bất kỳ lúc nào</li><li>Phù hợp cho việc lớn - không cần dùng cho câu hỏi nhanh</li></ul>`,
  },
  {
    slug: "vi-du-tu-dong-hoa",
    title: "Ví Dụ Thực Tế",
    categoryIndex: 3,
    html: `<h1>Ví Dụ Thực Tế: Tự Động Hóa</h1><h2>Ví dụ 1: Báo thời tiết mỗi sáng</h2><h3>Bạn muốn:</h3><p>Mỗi sáng thức dậy là biết thời tiết, không cần tự mở app</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mỗi sáng 7h tìm thời tiết TP.HCM và gửi cho tôi"</li></ul><h3>Kết quả:</h3><p>Mỗi sáng 7h, bạn nhận được tin nhắn: 'Hôm nay trời nắng, 32 độ, chiều có thể mưa rào'</p><h2>Ví dụ 2: Theo dõi trang web</h2><h3>Bạn muốn:</h3><p>Biết ngay khi trang web công ty bị sập</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mỗi 10 phút kiểm tra https://mysite.com, báo ngay nếu bị lỗi"</li></ul><h3>Kết quả:</h3><p>Nếu trang web sập, bạn nhận tin nhắn ngay: 'Trang web không truy cập được!'</p><h2>Ví dụ 3: Tóm tắt tin tức hàng ngày</h2><h3>Bạn muốn:</h3><p>Mỗi tối có bản tin tóm tắt, không cần đọc nhiều trang báo</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mỗi tối 8h tìm 10 tin công nghệ mới nhất, tóm tắt và gửi cho tôi"</li></ul><h3>Kết quả:</h3><p>Mỗi tối 8h, bạn nhận bản tin 10 tin tức tóm tắt gọn gàng</p><h2>Ví dụ 4: Nhắc lịch họp</h2><h3>Bạn muốn:</h3><p>Không bao giờ quên lịch họp</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mỗi ngày kiểm tra lịch và nhắc tôi 1 tiếng trước khi họp"</li></ul><h2>Ví dụ 5: Theo dõi giá</h2><h3>Bạn muốn:</h3><p>Biết ngay khi giá Bitcoin xuống dưới mức bạn muốn mua</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mỗi 15 phút check giá Bitcoin, báo khi xuống dưới 60,000 USD"</li></ul><h3>Kết quả:</h3><p>Khi giá đạt mức, bạn nhận tin nhắn: 'Bitcoin đã xuống 59,800 USD!'</p><h2>Ví dụ 6: Dọn dẹp máy tính</h2><h3>Bạn muốn:</h3><p>Tự động dọn file cũ trong thư mục Downloads</p><h3>Bạn chỉ cần nói:</h3><ul><li>"Mỗi Chủ Nhật kiểm tra thư mục Downloads, liệt kê file cũ hơn 30 ngày và hỏi tôi có xóa không"</li></ul>`,
  },
];

/** Find article by slug */
export function getDocArticle(slug: string): DocArticle | undefined {
  return DOC_ARTICLES.find((a) => a.slug === slug);
}

/** Get articles for a category */
export function getDocsByCategory(categoryIndex: number): DocArticle[] {
  return DOC_ARTICLES.filter((a) => a.categoryIndex === categoryIndex);
}
